AWSTemplateFormatVersion: '2010-09-09'
Description: Document SSM PowerShell avec gestion de versions

Resources:
  SSMDocument:
    Type: AWS::SSM::Document
    Properties:
      Name: "Test-Doc-versions"
      DocumentType: Command
      UpdateMethod: NewVersion # Crée une nouvelle version à chaque mise à jour
      Content:
        schemaVersion: '2.2'
        description: "Test SSM Document (v2)"
        mainSteps:
          - action: "aws:runPowerShellScript"
            name: displayversion
            inputs:
              runCommand:
                - |
                  Write-Host "Document version is 2"
                  # Ajoute ici les changements pour la version 2

  RunSSMDocumentV1:
    Type: AWS::SSM::Association
    Properties:
      Name: Test-Doc-versions
      DocumentVersion: "1" # Spécifie la version du document à utiliser
      Targets:
        - Key: InstanceIds
          Values:
            - i-0ee195831b91d1234 # Remplace par l'ID de ton instance cible
