Resources:
  GetSuffixLambdaFunction:
    Type: "AWS::Lambda::Function"
    Properties:
      Handler: "index.handler"
      Role: !GetAtt LambdaExecutionRole.Arn
      Timeout: 30
      Runtime: python3.13
      Code:
        ZipFile: |
          import json
          import boto3
          import urllib3
          import cfnresponse
          from datetime import datetime
             
          http = urllib3.PoolManager()

          def handler(event, context):
              try:
                  date = datetime.utcnow().strftime('%Y%m%d%H%M%S')
                
                  response_data = {
                      'Status': 'SUCCESS',
                      'dateSuffix': date
                  }
                  cfnresponse.send(event, context, cfnresponse.SUCCESS, response_data)
                  print("Response sent successfully.")
              except Exception as e:
                  print("Error:", e)
                  response_data = {
                      'Status': 'FAILED',
                      'Reason': str(e)
                  }
                  cfnresponse.send(event, context, cfnresponse.FAILED, response_data)


  GetSuffixCustomResource:
    Type: "Custom::GenerateSuffixName"
    Properties:
      ServiceToken: !GetAtt GetSuffixLambdaFunction.Arn

  S3Bucket:
    Type: "AWS::S3::Bucket"
    Properties:
      BucketName: !Sub 'my-bucket-${GetSuffixCustomResource.dateSuffix}'

  LambdaExecutionRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service: "lambda.amazonaws.com"
            Action: "sts:AssumeRole"
      Policies:
        - PolicyName: "LambdaExecutionPolicy"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action:
                  - "logs:CreateLogGroup"
                  - "logs:CreateLogStream"
                  - "logs:PutLogEvents"
                Resource: "*"
